# Generated by Django 3.1.6 on 2021-02-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0005_auto_20210212_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
